// File generated by firebase_options.dart extraction
// Project: finora-budget-app
// DO NOT EDIT — regenerate via: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp_tjm059LMIrR2Qlt7h51xlyCLzDnu_w',
    appId: '1:744645935730:android:3d29551860c09e6793b8eb',
    messagingSenderId: '744645935730',
    projectId: 'finora-budget-app',
    storageBucket: 'finora-budget-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp_tjm059LMIrR2Qlt7h51xlyCLzDnu_w',
    appId: '1:744645935730:android:3d29551860c09e6793b8eb',
    messagingSenderId: '744645935730',
    projectId: 'finora-budget-app',
    storageBucket: 'finora-budget-app.firebasestorage.app',
    authDomain: 'finora-budget-app.firebaseapp.com',
  );
}

